version: "3"
services:
  php-apache:
    build: ./php-apache
    ports:
      - 8056:80
    volumes:
      - ../_Sites:/app

  db:
    image: mysql:5.7
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
